import uuid

from django.conf import settings
from django.db import models


class Project(models.Model):
    """A folder, and the single PDF it holds.

    Per PRD §7.1 there is no separate DrawingFile table: one project owns one
    PDF, so the file's identity lives here. If a project ever needs to hold
    several PDFs, §7.2 describes the migration back out.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="projects"
    )
    name = models.CharField(max_length=200)
    filename = models.CharField(max_length=255)
    storage_path = models.CharField(max_length=512)
    size_bytes = models.BigIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "projects"
        # `id` breaks the tie. Without it, two folders created inside the same
        # clock tick come back in whatever order the database feels like,
        # which makes listings jump around between requests.
        ordering = ["-updated_at", "id"]
        indexes = [models.Index(fields=["owner", "-updated_at"])]

    def __str__(self):
        return self.name


class Drawing(models.Model):
    """One sheet. Its `id` is the drawing id annotations hang off."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="drawings")
    page_number = models.PositiveIntegerField()

    class Meta:
        db_table = "drawings"
        ordering = ["page_number"]
        constraints = [
            models.UniqueConstraint(
                fields=["project", "page_number"], name="unique_page_per_project"
            )
        ]

    def __str__(self):
        return f"{self.project.name} p{self.page_number}"


class Annotation(models.Model):
    class Kind(models.TextChoices):
        BLOCK = "block", "Block"
        CAPTURE = "capture", "Capture"

    # Generated by the client so that a retried save is idempotent: a dropped
    # response cannot turn one rectangle into two.
    id = models.UUIDField(primary_key=True, editable=False)
    drawing = models.ForeignKey(Drawing, on_delete=models.CASCADE, related_name="annotations")
    kind = models.CharField(max_length=16, choices=Kind.choices)

    # Normalized to the unrotated PDF page box, origin top-left. Never pixels:
    # this is what keeps a rectangle in place across zoom and window size.
    x = models.FloatField()
    y = models.FloatField()
    w = models.FloatField()
    h = models.FloatField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "annotations"
        ordering = ["created_at"]
        indexes = [models.Index(fields=["drawing", "kind"])]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(x__gte=0, x__lte=1, y__gte=0, y__lte=1),
                name="annotation_origin_within_page",
            ),
            models.CheckConstraint(
                condition=models.Q(w__gt=0, w__lte=1, h__gt=0, h__lte=1),
                name="annotation_size_within_page",
            ),
        ]

    def __str__(self):
        return f"{self.kind} on {self.drawing_id}"
