# Generated by Django 5.2.6 on 2026-09-10 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='drawings.project')),
            ],
            options={
                'db_table': 'drawings',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('block', 'Block'), ('capture', 'Capture')], max_length=16)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='drawings.drawing')),
            ],
            options={
                'db_table': 'annotations',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['drawing', 'kind'], name='annotations_drawing_5e2375_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('x__gte', 0), ('x__lte', 1), ('y__gte', 0), ('y__lte', 1)), name='annotation_origin_within_page'), models.CheckConstraint(condition=models.Q(('h__gt', 0), ('h__lte', 1), ('w__gt', 0), ('w__lte', 1)), name='annotation_size_within_page')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-updated_at'], name='projects_owner_i_fc804a_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawing',
            constraint=models.UniqueConstraint(fields=('project', 'page_number'), name='unique_page_per_project'),
        ),
    ]
