# Generated by Django 5.2.6 on 2026-09-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at', 'id']},
        ),
    ]
